[project]
name = "mldetection-jetson"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "supervision>=0.26.1",
    "ultralytics>=8.3.228",
]
